#ifndef MYGFX_CONFIG_H_HEADER_GUARD
#define MYGFX_CONFIG_H_HEADER_GUARD

#include <bx/bx.h>

#ifndef MYGFX_CONFIG_DEBUG
#	define MYGFX_CONFIG_DEBUG 0
#endif // MYGFX_CONFIG_DEBUG

#if !defined(MYGFX_CONFIG_RENDERER_DIRECT3D9)  \
 && !defined(MYGFX_CONFIG_RENDERER_DIRECT3D11) \
 && !defined(MYGFX_CONFIG_RENDERER_DIRECT3D12) \
 && !defined(MYGFX_CONFIG_RENDERER_METAL)      \
 && !defined(MYGFX_CONFIG_RENDERER_OPENGL)     \
 && !defined(MYGFX_CONFIG_RENDERER_OPENGLES)   \
 && !defined(MYGFX_CONFIG_RENDERER_VULKAN)    

#	ifndef MYGFX_CONFIG_RENDERER_DIRECT3D9
#		define MYGFX_CONFIG_RENDERER_DIRECT3D9 (0 \
					|| BX_PLATFORM_WINDOWS       \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_DIRECT3D9

#	ifndef MYGFX_CONFIG_RENDERER_DIRECT3D11
#		define MYGFX_CONFIG_RENDERER_DIRECT3D11 (0 \
					|| BX_PLATFORM_WINDOWS        \
					|| BX_PLATFORM_WINRT          \
					|| BX_PLATFORM_XBOXONE        \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_DIRECT3D11

#	ifndef MYGFX_CONFIG_RENDERER_DIRECT3D12
#		define MYGFX_CONFIG_RENDERER_DIRECT3D12 (0 \
					|| BX_PLATFORM_WINDOWS        \
					|| BX_PLATFORM_WINRT          \
					|| BX_PLATFORM_XBOXONE        \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_DIRECT3D12

#	ifndef MYGFX_CONFIG_RENDERER_METAL
#		define MYGFX_CONFIG_RENDERER_METAL (0           \
					|| (BX_PLATFORM_IOS && BX_CPU_ARM) \
					|| (BX_PLATFORM_OSX >= 101100)     \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_METAL

#	ifndef MYGFX_CONFIG_RENDERER_OPENGL
#		define MYGFX_CONFIG_RENDERER_OPENGL (0 \
					|| BX_PLATFORM_BSD        \
					|| BX_PLATFORM_LINUX      \
					|| BX_PLATFORM_OSX        \
					|| BX_PLATFORM_WINDOWS    \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_OPENGL

#	ifndef MYGFX_CONFIG_RENDERER_OPENGLES
#		define MYGFX_CONFIG_RENDERER_OPENGLES (0 \
					|| BX_PLATFORM_ANDROID      \
					|| BX_PLATFORM_EMSCRIPTEN   \
					|| BX_PLATFORM_IOS          \
					|| BX_PLATFORM_RPI          \
					|| BX_PLATFORM_STEAMLINK    \
					|| BX_PLATFORM_NX           \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_OPENGLES

#	ifndef MYGFX_CONFIG_RENDERER_VULKAN
#		define MYGFX_CONFIG_RENDERER_VULKAN (0 \
					|| BX_PLATFORM_ANDROID    \
					|| BX_PLATFORM_LINUX      \
					|| BX_PLATFORM_WINDOWS    \
					|| BX_PLATFORM_NX         \
					? 1 : 0)
#	endif // MYGFX_CONFIG_RENDERER_VULKAN

#else

#	ifndef MYGFX_CONFIG_RENDERER_DIRECT3D9
#		define MYGFX_CONFIG_RENDERER_DIRECT3D9 0
#	endif // MYGFX_CONFIG_RENDERER_DIRECT3D9

#	ifndef MYGFX_CONFIG_RENDERER_DIRECT3D11
#		define MYGFX_CONFIG_RENDERER_DIRECT3D11 0
#	endif // MYGFX_CONFIG_RENDERER_DIRECT3D11

#	ifndef MYGFX_CONFIG_RENDERER_DIRECT3D12
#		define MYGFX_CONFIG_RENDERER_DIRECT3D12 0
#	endif // MYGFX_CONFIG_RENDERER_DIRECT3D12

#	ifndef MYGFX_CONFIG_RENDERER_METAL
#		define MYGFX_CONFIG_RENDERER_METAL 0
#	endif // MYGFX_CONFIG_RENDERER_METAL

#	ifndef MYGFX_CONFIG_RENDERER_OPENGL
#		define MYGFX_CONFIG_RENDERER_OPENGL 0
#	endif // MYGFX_CONFIG_RENDERER_OPENGL

#	ifndef MYGFX_CONFIG_RENDERER_OPENGLES
#		define MYGFX_CONFIG_RENDERER_OPENGLES 0
#	endif // MYGFX_CONFIG_RENDERER_OPENGLES

#	ifndef MYGFX_CONFIG_RENDERER_VULKAN
#		define MYGFX_CONFIG_RENDERER_VULKAN 0
#	endif // MYGFX_CONFIG_RENDERER_VULKAN

#endif

#if MYGFX_CONFIG_RENDERER_OPENGL && MYGFX_CONFIG_RENDERER_OPENGL < 21
#	undef MYGFX_CONFIG_RENDERER_OPENGL
#	define MYGFX_CONFIG_RENDERER_OPENGL 21
#endif // MYGFX_CONFIG_RENDERER_OPENGL && MYGFX_CONFIG_RENDERER_OPENGL < 21

#if MYGFX_CONFIG_RENDERER_OPENGLES && MYGFX_CONFIG_RENDERER_OPENGLES < 20
#	undef MYGFX_CONFIG_RENDERER_OPENGLES
#	define MYGFX_CONFIG_RENDERER_OPENGLES 20
#endif // MYGFX_CONFIG_RENDERER_OPENGLES && MYGFX_CONFIG_RENDERER_OPENGLES < 20

#if MYGFX_CONFIG_RENDERER_OPENGL && MYGFX_CONFIG_RENDERER_OPENGLES
#	error "Can't define both MYGFX_CONFIG_RENDERER_OPENGL and MYGFX_CONFIG_RENDERER_OPENGLES"
#endif // MYGFX_CONFIG_RENDERER_OPENGL && MYGFX_CONFIG_RENDERER_OPENGLES

/// Enable use of extensions.
#ifndef MYGFX_CONFIG_RENDERER_USE_EXTENSIONS
#	define MYGFX_CONFIG_RENDERER_USE_EXTENSIONS 1
#endif // MYGFX_CONFIG_RENDERER_USE_EXTENSIONS

// Enable nVidia PerfHUD integration.
#ifndef MYGFX_CONFIG_DEBUG_PERFHUD
#	define MYGFX_CONFIG_DEBUG_PERFHUD 0
#endif // MYGFX_CONFIG_DEBUG_NVPERFHUD

/// Enable PIX markers.
#ifndef MYGFX_CONFIG_DEBUG_PIX
#	define MYGFX_CONFIG_DEBUG_PIX MYGFX_CONFIG_DEBUG
#endif // MYGFX_CONFIG_DEBUG_PIX

/// Enable DX11 object names.
#ifndef MYGFX_CONFIG_DEBUG_OBJECT_NAME
#	define MYGFX_CONFIG_DEBUG_OBJECT_NAME MYGFX_CONFIG_DEBUG
#endif // MYGFX_CONFIG_DEBUG_OBJECT_NAME

/// Enable Metal markers.
#ifndef MYGFX_CONFIG_DEBUG_MTL
#	define MYGFX_CONFIG_DEBUG_MTL MYGFX_CONFIG_DEBUG
#endif // MYGFX_CONFIG_DEBUG_MTL

/// Enable uniform debug checks.
#ifndef MYGFX_CONFIG_DEBUG_UNIFORM
#	define MYGFX_CONFIG_DEBUG_UNIFORM MYGFX_CONFIG_DEBUG
#endif // MYGFX_CONFIG_DEBUG_UNIFORM

/// Enable occlusion debug checks.
#ifndef MYGFX_CONFIG_DEBUG_OCCLUSION
#	define MYGFX_CONFIG_DEBUG_OCCLUSION MYGFX_CONFIG_DEBUG
#endif // MYGFX_CONFIG_DEBUG_OCCLUSION

#ifndef MYGFX_CONFIG_MULTITHREADED
//#	define MYGFX_CONFIG_MULTITHREADED ( (0 == BX_PLATFORM_EMSCRIPTEN) ? 1 : 0)
#	define MYGFX_CONFIG_MULTITHREADED 0   //( (0 == BX_PLATFORM_EMSCRIPTEN) ? 1 : 0)
#endif // MYGFX_CONFIG_MULTITHREADED

#ifndef MYGFX_CONFIG_MAX_DRAW_CALLS
#	define MYGFX_CONFIG_MAX_DRAW_CALLS ( (64<<10)-1)
#endif // MYGFX_CONFIG_MAX_DRAW_CALLS

#ifndef MYGFX_CONFIG_MAX_BLIT_ITEMS
#	define MYGFX_CONFIG_MAX_BLIT_ITEMS (1<<10)
#endif // MYGFX_CONFIG_MAX_BLIT_ITEMS

#ifndef MYGFX_CONFIG_MAX_MATRIX_CACHE
#	define MYGFX_CONFIG_MAX_MATRIX_CACHE (MYGFX_CONFIG_MAX_DRAW_CALLS+1)
#endif // MYGFX_CONFIG_MAX_MATRIX_CACHE

#ifndef MYGFX_CONFIG_MAX_RECT_CACHE
#	define MYGFX_CONFIG_MAX_RECT_CACHE (4<<10)
#endif //  MYGFX_CONFIG_MAX_RECT_CACHE

#ifndef MYGFX_CONFIG_SORT_KEY_NUM_BITS_DEPTH
#	define MYGFX_CONFIG_SORT_KEY_NUM_BITS_DEPTH 32
#endif // MYGFX_CONFIG_SORT_KEY_NUM_BITS_DEPTH

#ifndef MYGFX_CONFIG_SORT_KEY_NUM_BITS_SEQ
#	define MYGFX_CONFIG_SORT_KEY_NUM_BITS_SEQ 20
#endif // MYGFX_CONFIG_SORT_KEY_NUM_BITS_SEQ

#ifndef MYGFX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM
#	define MYGFX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM 9
#endif // MYGFX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM

// Cannot be configured via compiler options.
#define MYGFX_CONFIG_MAX_PROGRAMS (1<<MYGFX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM)
BX_STATIC_ASSERT(bx::isPowerOf2(MYGFX_CONFIG_MAX_PROGRAMS), "MYGFX_CONFIG_MAX_PROGRAMS must be power of 2.");

#ifndef MYGFX_CONFIG_MAX_VIEWS
#	define MYGFX_CONFIG_MAX_VIEWS 256
#endif // MYGFX_CONFIG_MAX_VIEWS
BX_STATIC_ASSERT(bx::isPowerOf2(MYGFX_CONFIG_MAX_VIEWS), "MYGFX_CONFIG_MAX_VIEWS must be power of 2.");

#define MYGFX_CONFIG_MAX_VIEW_NAME_RESERVED 6

#ifndef MYGFX_CONFIG_MAX_VIEW_NAME
#	define MYGFX_CONFIG_MAX_VIEW_NAME 256
#endif // MYGFX_CONFIG_MAX_VIEW_NAME

#ifndef MYGFX_CONFIG_MAX_VERTEX_DECLS
#	define MYGFX_CONFIG_MAX_VERTEX_DECLS 64
#endif // MYGFX_CONFIG_MAX_VERTEX_DECLS

#ifndef MYGFX_CONFIG_MAX_INDEX_BUFFERS
#	define MYGFX_CONFIG_MAX_INDEX_BUFFERS (4<<10)
#endif // MYGFX_CONFIG_MAX_INDEX_BUFFERS

#ifndef MYGFX_CONFIG_MAX_VERTEX_BUFFERS
#	define MYGFX_CONFIG_MAX_VERTEX_BUFFERS (4<<10)
#endif // MYGFX_CONFIG_MAX_VERTEX_BUFFERS

#ifndef MYGFX_CONFIG_MAX_VERTEX_STREAMS
#	define MYGFX_CONFIG_MAX_VERTEX_STREAMS 4
#endif // MYGFX_CONFIG_MAX_VERTEX_STREAMS

#ifndef MYGFX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS
#	define MYGFX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS (4<<10)
#endif // MYGFX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS

#ifndef MYGFX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS
#	define MYGFX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS (4<<10)
#endif // MYGFX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS

#ifndef MYGFX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE
#	define MYGFX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE (1<<20)
#endif // MYGFX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE

#ifndef MYGFX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE
#	define MYGFX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE (3<<20)
#endif // MYGFX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE

#ifndef MYGFX_CONFIG_MAX_SHADERS
#	define MYGFX_CONFIG_MAX_SHADERS 512
#endif // MYGFX_CONFIG_MAX_FRAGMENT_SHADERS

#ifndef MYGFX_CONFIG_MAX_TEXTURES
#	define MYGFX_CONFIG_MAX_TEXTURES (4<<10)
#endif // MYGFX_CONFIG_MAX_TEXTURES

#ifndef MYGFX_CONFIG_MAX_TEXTURE_SAMPLERS
#	define MYGFX_CONFIG_MAX_TEXTURE_SAMPLERS 16
#endif // MYGFX_CONFIG_MAX_TEXTURE_SAMPLERS

#ifndef MYGFX_CONFIG_MAX_FRAME_BUFFERS
#	define MYGFX_CONFIG_MAX_FRAME_BUFFERS 128
#endif // MYGFX_CONFIG_MAX_FRAME_BUFFERS

#ifndef MYGFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS
#	define MYGFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS 8
#endif // MYGFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS

#ifndef MYGFX_CONFIG_MAX_UNIFORMS
#	define MYGFX_CONFIG_MAX_UNIFORMS 512
#endif // MYGFX_CONFIG_MAX_UNIFORMS

#ifndef MYGFX_CONFIG_MAX_OCCLUSION_QUERIES
#	define MYGFX_CONFIG_MAX_OCCLUSION_QUERIES 256
#endif // MYGFX_CONFIG_MAX_OCCLUSION_QUERIES

#ifndef MYGFX_CONFIG_MAX_COMMAND_BUFFER_SIZE
#	define MYGFX_CONFIG_MAX_COMMAND_BUFFER_SIZE (64<<10)
#endif // MYGFX_CONFIG_MAX_COMMAND_BUFFER_SIZE

#ifndef MYGFX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE
#	define MYGFX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE (6<<20)
#endif // MYGFX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE

#ifndef MYGFX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE
#	define MYGFX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE (2<<20)
#endif // MYGFX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE

#ifndef MYGFX_CONFIG_MAX_INSTANCE_DATA_COUNT
#	define MYGFX_CONFIG_MAX_INSTANCE_DATA_COUNT 5
#endif // MYGFX_CONFIG_MAX_INSTANCE_DATA_COUNT

#ifndef MYGFX_CONFIG_MAX_CLEAR_COLOR_PALETTE
#	define MYGFX_CONFIG_MAX_COLOR_PALETTE 16
#endif // MYGFX_CONFIG_MAX_CLEAR_COLOR_PALETTE

#define MYGFX_CONFIG_DRAW_INDIRECT_STRIDE 32

#ifndef MYGFX_CONFIG_PROFILER
#	define MYGFX_CONFIG_PROFILER 0
#endif // MYGFX_CONFIG_PROFILER

#ifndef MYGFX_CONFIG_RENDERDOC_LOG_FILEPATH
#	define MYGFX_CONFIG_RENDERDOC_LOG_FILEPATH "temp/bgfx"
#endif // MYGFX_CONFIG_RENDERDOC_LOG_FILEPATH

#ifndef MYGFX_CONFIG_RENDERDOC_CAPTURE_KEYS
#	define MYGFX_CONFIG_RENDERDOC_CAPTURE_KEYS { eRENDERDOC_Key_F11 }
#endif // MYGFX_CONFIG_RENDERDOC_CAPTURE_KEYS

#ifndef MYGFX_CONFIG_API_SEMAPHORE_TIMEOUT
#	define MYGFX_CONFIG_API_SEMAPHORE_TIMEOUT (5000)
#endif // MYGFX_CONFIG_API_SEMAPHORE_TIMEOUT

#ifndef MYGFX_CONFIG_MIP_LOD_BIAS
#	define MYGFX_CONFIG_MIP_LOD_BIAS 0
#endif // MYGFX_CONFIG_MIP_LOD_BIAS

#ifndef MYGFX_CONFIG_DEFAULT_MAX_ENCODERS
#	define MYGFX_CONFIG_DEFAULT_MAX_ENCODERS ( (0 != MYGFX_CONFIG_MULTITHREADED) ? 8 : 1)
#endif // MYGFX_CONFIG_DEFAULT_MAX_ENCODERS

#ifndef MYGFX_CONFIG_MAX_BACK_BUFFERS
#	define MYGFX_CONFIG_MAX_BACK_BUFFERS 4
#endif // MYGFX_CONFIG_MAX_BACK_BUFFERS

#endif